spring.application.name=API_Login_Page
spring.profiles.active=dev

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#AuthGogle

google.client.id=825930097023-rcqinabvp49hpmtik10usipufdpjvvcs.apps.googleusercontent.com